# Generated by Django 3.1.7 on 2021-03-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvlauthentication', '0002_auto_20210311_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manage',
        ),
    ]
