# Generated by Django 3.1.6 on 2021-02-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, null=True)),
                ('color_bus', models.CharField(max_length=50, null=True)),
                ('number_seat', models.IntegerField(null=True)),
                ('model_bus', models.TextField(max_length=100, null=True)),
                ('track_from_address', models.TextField(null=True)),
                ('track_to_address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Captin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=None, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField(default='')),
                ('to_address', models.TextField()),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.bus')),
                ('captin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.captin')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=100)),
                ('rate', models.IntegerField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.passenger')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField(null=True)),
                ('to_address', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.bus')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='swvl_admin.passenger')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.trip')),
            ],
        ),
    ]
