# Generated by Django 3.1.6 on 2021-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.passenger'),
        ),
    ]
