# Generated by Django 3.1.6 on 2021-02-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0003_auto_20210211_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='captin',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captin_name', to='swvl_admin.captin'),
        ),
    ]
