# Generated by Django 3.1.6 on 2021-02-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0004_auto_20210211_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='passenger',
        ),
    ]
