# Generated by Django 3.1.6 on 2021-02-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0005_remove_trip_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus',
        ),
    ]
