# Generated by Django 3.1.6 on 2021-02-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0006_remove_booking_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='track_from_address',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='track_to_address',
        ),
    ]
