# Generated by Django 3.1.6 on 2021-02-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0007_auto_20210215_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.bus'),
        ),
    ]
