# Generated by Django 3.1.6 on 2021-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0008_booking_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reserved',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_seat',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_date',
            field=models.TextField(null=True),
        ),
    ]
