# Generated by Django 3.1.6 on 2021-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0009_auto_20210222_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reserved_seats',
            field=models.IntegerField(null=True),
        ),
    ]
