# Generated by Django 3.1.6 on 2021-02-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0010_booking_reserved_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='reserved',
            field=models.IntegerField(null=True),
        ),
    ]
