# Generated by Django 3.1.6 on 2021-02-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0011_auto_20210223_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swvl_admin.bus'),
        ),
    ]
