# Generated by Django 3.1.6 on 2021-02-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0012_auto_20210223_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus',
        ),
    ]
