# Generated by Django 3.1.6 on 2021-02-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0013_remove_booking_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
