# Generated by Django 3.1.6 on 2021-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0015_auto_20210224_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='reserved',
            field=models.FloatField(null=True),
        ),
    ]
