# Generated by Django 3.1.6 on 2021-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0018_auto_20210227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
