# Generated by Django 3.1.6 on 2021-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0019_auto_20210227_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
