# Generated by Django 3.1.7 on 2021-03-02 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0023_auto_20210228_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 14, 19, 55, 718730)),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
