# Generated by Django 3.1.7 on 2021-03-05 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0027_auto_20210304_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 18, 37, 41, 930724)),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
