# Generated by Django 3.1.7 on 2021-03-07 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0029_auto_20210306_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 14, 43, 36, 935424)),
        ),
    ]
