# Generated by Django 3.1.7 on 2021-03-07 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0030_auto_20210307_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 28, 58, 946507)),
        ),
    ]
