# Generated by Django 3.1.7 on 2021-03-11 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swvl_admin', '0032_auto_20210311_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 5, 24, 39, 252562)),
        ),
    ]
